name: VSCode Marketplace Deploy / Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    name: Publish extension to VSCode Marketplace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Setup Yarn and Install Dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Publish extension
        run: ./node_modules/.bin/vsce publish -p $VSCE_PAT
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
